version: '3.8'

services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      args:
        VITE_MODE: development
    image: ide2-backend:v1
    pull_policy: build
    container_name: ide2-backend
    depends_on:
      postgres-dev:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:password@postgres-dev:5432/postgres"
      VITE_DEV_SERVER: "http://host.docker.internal:1420"
      JWT_SECRET: "dev-jwt-secret-change-this-in-production-f8a7d9e2c3b4a1f6e5d4c3b2a1f0e9d8"
      CERT_GATEWAY_KEY: "f66df295d068fc3b667e5bca0569ff4ce4938f3f974224625fdfb1008805c0f1"
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/index.ts:/usr/src/app/index.ts
      - ./backend/cluster.ts:/usr/src/app/cluster.ts
      - ./backend/prisma:/usr/src/app/prisma
      - ./backend/shared:/usr/src/app/shared
      - ./backend/agents-server:/usr/src/app/agents-server
      - ./backend/scripts:/usr/src/app/scripts
    command: bash -c "bunx prisma migrate dev --skip-seed && bun --watch index.ts"
    stdin_open: true
    tty: true

  prisma-studio:
    image: ide2-backend:v1
    pull_policy: never
    container_name: prisma-studio
    depends_on:
      backend:
        condition: service_started
      postgres-dev:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres-dev:5432/postgres"
    ports:
      - "5555:5555"
    working_dir: /usr/src/app
    command: bunx prisma studio

volumes:
  postgres-data:
